# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'CMPageTitleView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for CMPageTitleView

  pod 'Masonry'
  
target 'CMPageTitleViewTests' do
    inherit! :search_paths
    # Pods for testing

 end

  target 'CMPageTitleViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
